language: node_js
node_js:
  - '12'
cache:
  yarn: true
  directories:
    - "node_modules"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - yarn run lerna run prepublish
script:
  - yarn bootstrap
  - yarn build
  - yarn test
before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
deploy:
  provider: script
  script: 
  - yarn publish-ci
  skip_cleanup: true
  on:
    branch: master