name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 10.x ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: setup node  
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'          
      - name: yarn            
        run: |
          yarn
          yarn bootstrap
          yarn build
          yarn test          
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
